version: '{LazyCacheVersion}.{build}{LazyCacheVersionSuffix}'
image: Visual Studio 2017
configuration: Release
environment:
  LazyCacheVersion: 2.0.0
  LazyCacheVersionSuffix: -beta01
  LazyCacheAspNetCoreVersion: 2.0.0
  LazyCacheAspNetCoreVersionSuffix: -beta01
build_script:
- ps: '& .\build.ps1'
deploy: off